
INSERT INTO Abilities (name, description, image_file) 
VALUES  ('장갑', '받는 피해를 3 감소시킵니다.', 'armor.png'),
        ('방어', '적이 이 카드를 우선 공격합니다.', 'defense.png'),
        ('비행', '비행 능력이 없는 카드의 공격 대상이 되지 않습니다.', 'flying.png'),
        ('공격불가', '이 카드는 다른 카드를 공격할 수 없습니다.', 'cannot_attack.png'),
        ('독성', '이 카드가 처음 공격해서 피해를 주면 상대 카드는 즉시 사망합니다.', 'poisonous.png'),
        ('돌진', '이 카드는 게임이 시작할 때 공격합니다.', 'charge.png'),
        ('도약', '가장 오른쪽 카드를 우선 공격합니다.', 'leaf.png'),
        ('잠수', '가장 왼쪽 카드를 우선 공격합니다.', 'dive.png');

INSERT INTO Cards (name, description, cost, attack, health, image_file)
VALUES  ('개', '멍멍', 5, 3, 7, 'dog.png'),
        ('고양이', '...', 5, 5, 5, 'cat.png'),
        ('코끼리', '뿌우', 10, 6, 10, 'elephant.png'),
        ('쥐', '찍', 3, 2, 4, 'mouse.png'),
        ('뱀', '쉭식', 5, 3, 3, 'snake.png'),
        ('코뿔소', '...', 9, 8, 8, 'rhino.png'),
        ('늑대', '왈왈', 6, 5, 7, 'wolf.png'),
        ('말벌', '윙윙', 3, 2, 2, 'hornet.png'),
        ('거북이', '...', 5, 1, 8, 'turtle.png'),
        ('호랑이', '크르릉', 8, 6, 7, 'tiger.png'),
        ('독수리', '퍼덕', 7, 5, 7, 'eagle.png'),
        ('여우', '캥', 5, 3, 6, 'fox.png'),
        ('캥거루', '퉁퉁', 5, 3, 8, 'kangaroo.png'),
        ('염소', '음메', 3, 4, 3, 'goat.png'),
        ('독거미', '...', 4, 2, 3, 'spider.png'),
        ('개미', '...', 0, 1, 1, 'ant.png'),
        ('악어', '...', 7, 5, 8, 'crocodile.png'),
        ('개구리', '개굴', 2, 1, 5, 'frog.png'),
        ('까마귀', '까악', 3, 2, 5, 'crow.png'),
        ('오리너구리', '...', 3, 2, 2, 'platypus.png');



INSERT INTO Card_Abilities (card_ID, ability_ID)
VALUES
    ((SELECT card_ID FROM Cards WHERE name = '코끼리'),
     (SELECT ability_ID FROM Abilities WHERE name = '장갑')),
    ((SELECT card_ID FROM Cards WHERE name = '코끼리'),
     (SELECT ability_ID FROM Abilities WHERE name = '방어')),
    ((SELECT card_ID FROM Cards WHERE name = '뱀'),
     (SELECT ability_ID FROM Abilities WHERE name = '독성')),
    ((SELECT card_ID FROM Cards WHERE name = '코뿔소'),
     (SELECT ability_ID FROM Abilities WHERE name = '장갑')),
    ((SELECT card_ID FROM Cards WHERE name = '코뿔소'),
     (SELECT ability_ID FROM Abilities WHERE name = '돌진')),
    ((SELECT card_ID FROM Cards WHERE name = '말벌'),
     (SELECT ability_ID FROM Abilities WHERE name = '비행')),
    ((SELECT card_ID FROM Cards WHERE name = '말벌'),
     (SELECT ability_ID FROM Abilities WHERE name = '독성')),
    ((SELECT card_ID FROM Cards WHERE name = '거북이'),
     (SELECT ability_ID FROM Abilities WHERE name = '장갑')),
    ((SELECT card_ID FROM Cards WHERE name = '거북이'),
     (SELECT ability_ID FROM Abilities WHERE name = '방어')),
    ((SELECT card_ID FROM Cards WHERE name = '거북이'),
     (SELECT ability_ID FROM Abilities WHERE name = '공격불가')),
    ((SELECT card_ID FROM Cards WHERE name = '캥거루'),
     (SELECT ability_ID FROM Abilities WHERE name = '도약')),
    ((SELECT card_ID FROM Cards WHERE name = '독수리'),
     (SELECT ability_ID FROM Abilities WHERE name = '비행')),
    ((SELECT card_ID FROM Cards WHERE name = '까마귀'),
     (SELECT ability_ID FROM Abilities WHERE name = '비행')),
    ((SELECT card_ID FROM Cards WHERE name = '독거미'),
     (SELECT ability_ID FROM Abilities WHERE name = '독성')),
    ((SELECT card_ID FROM Cards WHERE name = '악어'),
     (SELECT ability_ID FROM Abilities WHERE name = '잠수')),
    ((SELECT card_ID FROM Cards WHERE name = '개구리'),
     (SELECT ability_ID FROM Abilities WHERE name = '잠수')),
    ((SELECT card_ID FROM Cards WHERE name = '오리너구리'),
     (SELECT ability_ID FROM Abilities WHERE name = '잠수')),
    ((SELECT card_ID FROM Cards WHERE name = '오리너구리'),
     (SELECT ability_ID FROM Abilities WHERE name = '독성')),
    ((SELECT card_ID FROM Cards WHERE name = '염소'),
     (SELECT ability_ID FROM Abilities WHERE name = '돌진'));
